sudo: required

services:
  - docker

before_install:
  - docker build -t devopsdemo4us/docker-react -f Dockerfile.dev .

script:
  - docker run devopsdemo4us/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ""
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: ""
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key:
    secure: $AWS_SECRET_KEY
